# Generated by Django 3.1.4 on 2021-10-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmngapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Mobile_number', models.IntegerField()),
                ('Location', models.CharField(max_length=20)),
                ('Event_name', models.CharField(max_length=20)),
                ('Budget', models.IntegerField()),
                ('Capacity', models.IntegerField()),
                ('Facilities_Required', models.TextField()),
            ],
            options={
                'db_table': 'eventmngapp_Bookings',
            },
        ),
        migrations.CreateModel(
            name='EventCal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=20)),
                ('Event_date', models.DateField()),
                ('Event_time', models.TimeField()),
            ],
            options={
                'db_table': 'eventmngapp_EventCal',
            },
        ),
    ]
