# Generated by Django 3.1.4 on 2021-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmngapp', '0002_bookings_eventcal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events1',
            name='Facilities',
            field=models.TextField(),
        ),
    ]
